languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "DungPB"
copyright = "Copy, _right?_ :thinking_face:"

[params]
  isoCode = "en"
  dateFormat = "2 January 2006"
  #mainSections = ["section1", "section2"]
  description = "I am made of bones and skin, coffee, cigarettes, and 250 liters of alcohol."

[params.author]
  name = "Phan BÃ¡ DÅ©ng"
  image = "img/author.jpg"
  headline = "ðŸ¦€ created this blog with the purpose of storing various technology-related issues, sharing troubleshooting methods, and preserving personal memories."
  bio = "I am made of bones and skin, coffee, cigarettes, and 250 liters of alcohol."
  links = [
    { email = "mailto:me@dungpb.com" },
    { github = "https://github.com/badungphan99" },
    { linkedin = "https://www.linkedin.com/in/phanbadung" },
  ]
