languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "DungPB"
copyright = "Copy, _right?_ :thinking_face:"

[params]
  isoCode = "en"
  dateFormat = "2 January 2006"
  #mainSections = ["section1", "section2"]
  description = "I'm only human"

[params.author]
  name = "Phan BÃ¡ DÅ©ng"
  image = "img/author.jpg"
  headline = "I'm only human"
  bio = "Made from ğŸ’€ ğŸ«¥ â˜•ï¸ ğŸš¬ 2ï¸âƒ£5ï¸âƒ£0ï¸âƒ£ ğŸº"
  links = [
    { email = "mailto:me@dungpb.com" },
    { github = "https://github.com/badungphan99" },
    { linkedin = "https://www.linkedin.com/in/phanbadung" },
    { steam = "https://steamcommunity.com/id/dungpb/" },
    { telegram = "https://t.me/dungpb" },
  ]
